#include <iostream>
#include <random> // for std::mt19937 and std::uniform_int_distribution
#include <chrono>

unsigned int get_random_dev_value(){
	std::random_device rd{};
	return rd();
}

int main(){

	// Seed our Mersenne Twister using steady_clock
	long unix_time   { std::chrono::steady_clock::now().time_since_epoch().count() };
	std::mt19937 mt  { static_cast<std::mt19937::result_type>(unix_time) };

	// Seed using random_device
	unsigned int rd	 { get_random_dev_value() };
	std::mt19937 mt2 { rd };
	std::cout << typeid(std::random_device{}()).name() << '\n'; // Prints type 'j' -> unsigned int
	std::cout << rd << '\n'; // Prints random number generated by OS entropy 

	// Create a reusable random number gen that gens uniform numbers between 1 and 6
	std::uniform_int_distribution die6{ 1, 6 };

	for (int count{ 1 }; count <= 40; ++count){

		std::cout << die6(mt2) << '\t';

		// If we've printed 10 numbers, start a new row
		if (count % 10 == 0)
			std::cout << '\n';
	}
	return 0;
}
